vich_uploader:
    db_driver: orm

    mappings:
        products:
            uri_prefix: /uploads/products
            upload_destination: '%kernel.project_dir%/public/uploads/products'
            inject_on_load: true
